use winit::keyboard::KeyCode;

pub trait Ext {
    fn name(&self) -> &'static str;
}

impl Ext for KeyCode {
    fn name(&self) -> &'static str {
        return match self {
            KeyCode::Backquote => "`",
            KeyCode::Backslash => "\\",
            KeyCode::BracketLeft => "[",
            KeyCode::BracketRight => "]",
            KeyCode::Comma => ",",
            KeyCode::Digit0 => "0",
            KeyCode::Digit1 => "1",
            KeyCode::Digit2 => "2",
            KeyCode::Digit3 => "3",
            KeyCode::Digit4 => "4",
            KeyCode::Digit5 => "5",
            KeyCode::Digit6 => "6",
            KeyCode::Digit7 => "7",
            KeyCode::Digit8 => "8",
            KeyCode::Digit9 => "9",
            KeyCode::Equal => "=",
            KeyCode::KeyA => "A",
            KeyCode::KeyB => "B",
            KeyCode::KeyC => "C",
            KeyCode::KeyD => "D",
            KeyCode::KeyE => "E",
            KeyCode::KeyF => "F",
            KeyCode::KeyG => "G",
            KeyCode::KeyH => "H",
            KeyCode::KeyI => "I",
            KeyCode::KeyJ => "J",
            KeyCode::KeyK => "K",
            KeyCode::KeyL => "L",
            KeyCode::KeyM => "M",
            KeyCode::KeyN => "N",
            KeyCode::KeyO => "O",
            KeyCode::KeyP => "P",
            KeyCode::KeyQ => "Q",
            KeyCode::KeyR => "R",
            KeyCode::KeyS => "S",
            KeyCode::KeyT => "T",
            KeyCode::KeyU => "U",
            KeyCode::KeyV => "V",
            KeyCode::KeyW => "W",
            KeyCode::KeyX => "X",
            KeyCode::KeyY => "Y",
            KeyCode::KeyZ => "Z",
            KeyCode::Minus => "-",
            KeyCode::Period => ".",
            KeyCode::Quote => "'",
            KeyCode::Semicolon => ";",
            KeyCode::Slash => "/",
            KeyCode::AltLeft => "LEFT ALT",
            KeyCode::AltRight => "RIGHT ALT",
            KeyCode::Backspace => "BACKSPACE",
            KeyCode::CapsLock => "CAPS LOCK",
            KeyCode::ContextMenu => "MENU",
            KeyCode::ControlLeft => "LEFT CTRL",
            KeyCode::ControlRight => "RIGHT CTRL",
            KeyCode::Enter => "ENTER",
            KeyCode::SuperLeft => "LEFT SUPER",
            KeyCode::SuperRight => "RIGHT SUPER",
            KeyCode::ShiftLeft => "LEFT SHIFT",
            KeyCode::ShiftRight => "RIGHT SHIFT",
            KeyCode::Space => "SPACE",
            KeyCode::Tab => "TAB",
            KeyCode::Delete => "DELETE",
            KeyCode::End => "END",
            KeyCode::Help => "HELP",
            KeyCode::Home => "HOME",
            KeyCode::Insert => "INSERT",
            KeyCode::PageDown => "PAGE DOWN",
            KeyCode::PageUp => "PAGE UP",
            KeyCode::ArrowDown => "DOWN",
            KeyCode::ArrowLeft => "LEFT",
            KeyCode::ArrowRight => "RIGHT",
            KeyCode::ArrowUp => "UP",
            _ => "UNKNOWN",
        };
    }
}
